import { IActivity } from "../types";

export const dummyActivities: IActivity[] = [
  {
    id: "1",
    moduleId: "1",
    activityType: "Föreläsning",
    name: "Introduktion till HTML",
    startDate: "2023-08-15",
    endDate: "2023-08-16",
    status: "Genomförd",
    description: "Bra aktivitet!",
    feedback: "Bra!",
  },
  {
    id: "2",
    moduleId: "1",
    activityType: "Övning",
    name: "Skapa en webbsida",
    startDate: "2023-08-16",
    status: "Genomförd",
    description: "Bra aktivitet!",
  },
  {
    id: "3",
    moduleId: "2",
    activityType: "Föreläsning",
    name: "CSS styling",
    startDate: "2023-08-18",
    status: "Genomförd",
    feedback: "Bra arbete med responsiv design!",
  },
  {
    id: "4",
    moduleId: "3",
    activityType: "Inlämning",
    name: "Personlig webbsida",
    startDate: "2023-09-01",
    status: "Försenad",
  },
  {
    id: "5",
    moduleId: "3",
    activityType: "Inlämning",
    name: "Personlig webbsida",
    startDate: "2023-09-01",
    status: "Försenad",
  },

  {
    id: "6",
    moduleId: "4",
    activityType: "Inlämning",
    name: "Personlig webbsida",
    startDate: "2023-09-01",
    // status: "Försenad",
  },
  {
    id: "7",
    moduleId: "4",
    activityType: "Inlämning",
    name: "Personlig webbsida",
    startDate: "2023-09-01",
    status: "Godkänd",
  },
];
